"""Cloudflare colo → 中文节点名 + ISO 国家码（Netrvin/cloudflare-colo-list 快照）。
格式: {colo_code: [cca2, "中文国名·城市"]}。城市无中文映射时保留英文。
可用 geoip.ensure_colo_data() 在线刷新。"""

COLO_ZH = {
    'AAE': ['DZ', '阿尔及利亚·Annabah'],
    'ABJ': ['CI', '科特迪瓦·阿比让'],
    'ABQ': ['US', '美国·Albuquerque'],
    'ACC': ['GH', '加纳·阿克拉'],
    'ACX': ['CN', '中国·兴义'],
    'ADB': ['TR', '土耳其·Izmir'],
    'ADD': ['ET', '埃塞俄比亚·亚的斯亚贝巴'],
    'ADL': ['AU', '澳大利亚·阿德莱德'],
    'AGR': ['IN', '印度'],
    'AIP': ['IN', '印度'],
    'AKL': ['NZ', '新西兰·奥克兰'],
    'AKX': ['KZ', '哈萨克斯坦·Aktyubinsk'],
    'ALA': ['KZ', '哈萨克斯坦·Almaty'],
    'ALG': ['DZ', '阿尔及利亚·Algiers'],
    'AMD': ['IN', '印度·艾哈迈达巴德'],
    'AMM': ['JO', '约旦·安曼'],
    'AMS': ['NL', '荷兰·阿姆斯特丹'],
    'ANC': ['US', '美国·安克雷奇'],
    'ARI': ['CL', '智利·Arica'],
    'ARN': ['SE', '瑞典·斯德哥尔摩'],
    'ARU': ['BR', '巴西·Aracatuba'],
    'ASK': ['CI', '科特迪瓦·Yamoussoukro'],
    'ASU': ['PY', '巴拉圭·亚松森'],
    'ATH': ['GR', '希腊·雅典'],
    'ATL': ['US', '美国·亚特兰大'],
    'AUS': ['US', '美国·奥斯汀'],
    'AVA': ['CN', '中国·Anshun'],
    'BAH': ['BH', '巴林·麦纳麦'],
    'BAQ': ['CO', '哥伦比亚·Barranquilla'],
    'BBI': ['IN', '印度·Bhubaneswar'],
    'BCN': ['ES', '西班牙·巴塞罗那'],
    'BDQ': ['IN', '印度·Vadodara'],
    'BEG': ['RS', '塞尔维亚·贝尔格莱德'],
    'BEL': ['BR', '巴西·Belem'],
    'BEY': ['LB', '黎巴嫩·贝鲁特'],
    'BGI': ['BB', '巴巴多斯·布里奇敦'],
    'BGR': ['US', '美国·Bangor'],
    'BGW': ['IQ', '伊拉克·巴格达'],
    'BKK': ['TH', '泰国·曼谷'],
    'BLR': ['IN', '印度·班加罗尔'],
    'BNA': ['US', '美国·纳什维尔'],
    'BNE': ['AU', '澳大利亚·布里斯班'],
    'BOD': ['FR', '法国·Bordeaux/Merignac'],
    'BOG': ['CO', '哥伦比亚·波哥大'],
    'BOM': ['IN', '印度·孟买'],
    'BOS': ['US', '美国·波士顿'],
    'BRU': ['BE', '比利时·布鲁塞尔'],
    'BSB': ['BR', '巴西·Brasilia'],
    'BSR': ['IQ', '伊拉克·Basrah'],
    'BTS': ['SK', '斯洛伐克·Bratislava'],
    'BUD': ['HU', '匈牙利·Budapest'],
    'BUF': ['US', '美国·Buffalo'],
    'BWN': ['BN', '文莱·Bandar Seri Begawan'],
    'CAI': ['EG', '埃及·开罗'],
    'CAN': ['CN', '中国·广州'],
    'CAW': ['BR', '巴西·Campos Dos Goytacazes'],
    'CBR': ['AU', '澳大利亚·堪培拉'],
    'CCU': ['IN', '印度·加尔各答'],
    'CDG': ['FR', '法国·巴黎'],
    'CEB': ['PH', '菲律宾·Lapu-Lapu City'],
    'CFC': ['BR', '巴西·Caçador'],
    'CGB': ['BR', '巴西·Cuiaba'],
    'CGD': ['CN', '中国·Changde'],
    'CGK': ['ID', '印度尼西亚·雅加达'],
    'CGO': ['CN', '中国·郑州'],
    'CGP': ['BD', '孟加拉国·Chittagong'],
    'CGY': ['PH', '菲律宾·Cagayan De Oro City'],
    'CHC': ['NZ', '新西兰·Christchurch'],
    'CJB': ['IN', '印度·Coimbatore'],
    'CKG': ['CN', '中国·重庆'],
    'CLE': ['US', '美国·克利夫兰'],
    'CLO': ['CO', '哥伦比亚·Cali'],
    'CLT': ['US', '美国·夏洛特'],
    'CMB': ['LK', '斯里兰卡·科伦坡'],
    'CMH': ['US', '美国·哥伦布'],
    'CNF': ['BR', '巴西·Belo Horizonte'],
    'CNN': ['IN', '印度·Mattanur'],
    'CNX': ['TH', '泰国·Chiang Mai'],
    'COK': ['IN', '印度·Cochin'],
    'COR': ['AR', '阿根廷·Cordoba'],
    'CPH': ['DK', '丹麦·哥本哈根'],
    'CPT': ['ZA', '南非·开普敦'],
    'CRK': ['PH', '菲律宾·Angeles City'],
    'CSX': ['CN', '中国·长沙'],
    'CTU': ['CN', '中国·成都'],
    'CVG': ['US', '美国·Hebron'],
    'CWB': ['BR', '巴西·Curitiba'],
    'CZL': ['DZ', '阿尔及利亚·Constantine'],
    'CZX': ['CN', '中国·Changzhou'],
    'DAC': ['BD', '孟加拉国·达卡'],
    'DAD': ['VN', '越南·Da Nang'],
    'DAR': ['TZ', '坦桑尼亚·Dar es Salaam'],
    'DEL': ['IN', '印度·新德里'],
    'DEN': ['US', '美国·丹佛'],
    'DFW': ['US', '美国·Dallas-Fort Worth'],
    'DKR': ['SN', '塞内加尔·达喀尔'],
    'DLA': ['CM', '喀麦隆·Douala'],
    'DLC': ['CN', '中国·大连'],
    'DME': ['RU', '俄罗斯·莫斯科'],
    'DMM': ['SA', '沙特阿拉伯·Ad Dammam'],
    'DOH': ['QA', '卡塔尔·多哈'],
    'DPS': ['ID', '印度尼西亚·Denpasar-Bali Island'],
    'DTW': ['US', '美国·底特律'],
    'DUB': ['IE', '爱尔兰·都柏林'],
    'DUR': ['ZA', '南非·德班'],
    'DUS': ['DE', '德国·Dusseldorf'],
    'DXB': ['AE', '阿联酋·迪拜'],
    'EBB': ['UG', '乌干达·坎帕拉'],
    'EBL': ['IQ', '伊拉克·Arbil'],
    'EVN': ['AM', '亚美尼亚·埃里温'],
    'EWR': ['US', '美国·Newark'],
    'EZE': ['AR', '阿根廷·Ezeiza'],
    'FCO': ['IT', '意大利·罗马'],
    'FIH': ['CD', '刚果(金)·Kinshasa'],
    'FLN': ['BR', '巴西·Florianopolis'],
    'FOC': ['CN', '中国·福州'],
    'FOR': ['BR', '巴西·Fortaleza'],
    'FRA': ['DE', '德国·法兰克福'],
    'FRU': ['KG', '吉尔吉斯斯坦·Bishkek'],
    'FSD': ['US', '美国·Sioux Falls'],
    'FUK': ['JP', '日本·福冈'],
    'FUO': ['CN', '中国·Foshan'],
    'GBE': ['BW', '博茨瓦纳·Gaborone'],
    'GDL': ['MX', '墨西哥·瓜达拉哈拉'],
    'GEO': ['GY', '圭亚那·Georgetown'],
    'GIG': ['BR', '巴西·Rio De Janeiro'],
    'GND': ['GD', "格林纳达·Saint George's"],
    'GOT': ['SE', '瑞典·Gothenburg'],
    'GRU': ['BR', '巴西·Sao Paulo'],
    'GUA': ['GT', '危地马拉'],
    'GUM': ['GU', '关岛·Hagatna'],
    'GVA': ['CH', '瑞士·日内瓦'],
    'GYD': ['AZ', '阿塞拜疆·巴库'],
    'GYE': ['EC', '厄瓜多尔·瓜亚基尔'],
    'GYN': ['BR', '巴西·Goiania'],
    'HAK': ['CN', '中国·Haikou'],
    'HAM': ['DE', '德国·汉堡'],
    'HAN': ['VN', '越南·河内'],
    'HBA': ['AU', '澳大利亚·霍巴特'],
    'HEL': ['FI', '芬兰·赫尔辛基'],
    'HFA': ['IL', '以色列·海法'],
    'HGH': ['CN', '中国·Shaoxing'],
    'HKG': ['HK', '中国香港'],
    'HNL': ['US', '美国·火奴鲁鲁'],
    'HRE': ['ZW', '津巴布韦·Harare'],
    'HYD': ['IN', '印度·海得拉巴'],
    'HYN': ['CN', '中国·Taizhou'],
    'IAD': ['US', '美国·Dulles'],
    'IAH': ['US', '美国·休斯敦'],
    'ICN': ['KR', '韩国·首尔'],
    'IND': ['US', '美国·印第安纳波利斯'],
    'ISB': ['PK', '巴基斯坦·Islamabad'],
    'IST': ['TR', '土耳其·Arnavutkoy'],
    'ISU': ['IQ', '伊拉克·Sulaymaniyah'],
    'IXC': ['IN', '印度·Chandigarh'],
    'JAX': ['US', '美国·Jacksonville'],
    'JDO': ['BR', '巴西·Juazeiro Do Norte'],
    'JED': ['SA', '沙特阿拉伯·吉达'],
    'JHB': ['MY', '马来西亚·Senai'],
    'JIB': ['DJ', '吉布提'],
    'JNB': ['ZA', '南非·约翰内斯堡'],
    'JOG': ['ID', '印度尼西亚·Yogyakarta-Java Island'],
    'JOI': ['BR', '巴西·Joinville'],
    'JRG': ['IN', '印度·Jharsuguda'],
    'JXG': ['CN', '中国·Jiaxing'],
    'KBP': ['UA', '乌克兰·Kiev'],
    'KCH': ['MY', '马来西亚·Kuching'],
    'KEF': ['IS', '冰岛·雷克雅未克'],
    'KGL': ['RW', '卢旺达·Kigali'],
    'KHH': ['TW', '中国台湾·Kaohsiung City'],
    'KHI': ['PK', '巴基斯坦·Karachi'],
    'KHN': ['CN', '中国·Xinyu'],
    'KIN': ['JM', '牙买加·金斯敦'],
    'KIV': ['MD', '摩尔多瓦·Chișinău'],
    'KIX': ['JP', '日本·大阪'],
    'KJA': ['RU', '俄罗斯·Krasnoyarsk'],
    'KMG': ['CN', '中国·昆明'],
    'KNU': ['IN', '印度·Kanpur'],
    'KTM': ['NP', '尼泊尔·加德满都'],
    'KUL': ['MY', '马来西亚·吉隆坡'],
    'KWE': ['CN', '中国·贵阳'],
    'KWI': ['KW', '科威特'],
    'LAD': ['AO', '安哥拉·Luanda'],
    'LAS': ['US', '美国·拉斯维加斯'],
    'LAX': ['US', '美国·洛杉矶'],
    'LCA': ['CY', '塞浦路斯·Larnarca'],
    'LED': ['RU', '俄罗斯·St. Petersburg'],
    'LHE': ['PK', '巴基斯坦·Lahore'],
    'LHR': ['GB', '英国·伦敦'],
    'LHW': ['CN', '中国·兰州'],
    'LIM': ['PE', '秘鲁·利马'],
    'LIS': ['PT', '葡萄牙·里斯本'],
    'LJU': ['SI', '斯洛文尼亚·Ljubljana'],
    'LLK': ['AZ', '阿塞拜疆·Lankaran'],
    'LLW': ['MW', '马拉维·Lilongwe'],
    'LOS': ['NG', '尼日利亚·拉各斯'],
    'LPB': ['BO', '玻利维亚·La Paz / El Alto'],
    'LUN': ['ZM', '赞比亚·Lusaka'],
    'LUX': ['LU', '卢森堡·Luxembourg'],
    'LYA': ['CN', '中国·洛阳'],
    'LYS': ['FR', '法国·里昂'],
    'MAA': ['IN', '印度·金奈'],
    'MAD': ['ES', '西班牙·马德里'],
    'MAN': ['GB', '英国·Manchester'],
    'MAO': ['BR', '巴西·Manaus'],
    'MBA': ['KE', '肯尼亚·Mombasa'],
    'MCI': ['US', '美国·堪萨斯城'],
    'MCT': ['OM', '阿曼·马斯喀特'],
    'MDE': ['CO', '哥伦比亚·Rionegro'],
    'MEL': ['AU', '澳大利亚·墨尔本'],
    'MEM': ['US', '美国·孟菲斯'],
    'MEX': ['MX', '墨西哥'],
    'MFM': ['MO', '中国澳门·氹仔'],
    'MIA': ['US', '美国·迈阿密'],
    'MLA': ['MT', '马耳他·Luqa'],
    'MLE': ['MV', '马尔代夫·马累'],
    'MLG': ['ID', '印度尼西亚·Malang-Java Island'],
    'MNL': ['PH', '菲律宾·马尼拉'],
    'MPM': ['MZ', '莫桑比克·Maputo'],
    'MRS': ['FR', '法国·马赛'],
    'MRU': ['MU', '毛里求斯·路易港'],
    'MSP': ['US', '美国·明尼阿波利斯'],
    'MSQ': ['BY', '白俄罗斯·明斯克'],
    'MUC': ['DE', '德国·Munich'],
    'MXP': ['IT', '意大利·米兰'],
    'NAG': ['IN', '印度·Naqpur'],
    'NBO': ['KE', '肯尼亚·内罗毕'],
    'NJF': ['IQ', '伊拉克·Najaf'],
    'NOU': ['NC', '新喀里多尼亚·诺梅亚'],
    'NQN': ['AR', '阿根廷·Neuquen'],
    'NQZ': ['KZ', '哈萨克斯坦·Astana'],
    'NRT': ['JP', '日本·东京'],
    'NVT': ['BR', '巴西·Navegantes'],
    'OKA': ['JP', '日本·Naha'],
    'OKC': ['US', '美国·Oklahoma City'],
    'OMA': ['US', '美国·Omaha'],
    'ORD': ['US', '美国·芝加哥'],
    'ORF': ['US', '美国·Norfolk'],
    'ORN': ['DZ', '阿尔及利亚·Oran'],
    'OSL': ['NO', '挪威·奥斯陆'],
    'OTP': ['RO', '罗马尼亚·Bucharest'],
    'OUA': ['BF', '布基纳法索·Ouagadougou'],
    'PAT': ['IN', '印度·Patna'],
    'PBH': ['BT', '不丹·Paro'],
    'PBM': ['SR', '苏里南·Zandery'],
    'PDX': ['US', '美国·波特兰'],
    'PER': ['AU', '澳大利亚·珀斯'],
    'PHL': ['US', '美国·费城'],
    'PHX': ['US', '美国·凤凰城'],
    'PIT': ['US', '美国·Pittsburgh'],
    'PKX': ['CN', '中国·Langfang'],
    'PMO': ['IT', '意大利·Palermo'],
    'PMW': ['BR', '巴西·Palmas'],
    'PNH': ['KH', '柬埔寨·金边'],
    'PNQ': ['IN', '印度·浦那'],
    'POA': ['BR', '巴西·Porto Alegre'],
    'POS': ['TT', '特立尼达和多巴哥·西班牙港'],
    'PPT': ['PF', '法属波利尼西亚·帕皮提'],
    'PRG': ['CZ', '捷克·布拉格'],
    'PTY': ['PA', '巴拿马·Tocumen'],
    'QRO': ['MX', '墨西哥·Queretaro'],
    'QWJ': ['BR', '巴西·Americana'],
    'RAO': ['BR', '巴西·Ribeirao Preto'],
    'RDU': ['US', '美国·Raleigh/Durham'],
    'REC': ['BR', '巴西·Recife'],
    'RIC': ['US', '美国·里士满'],
    'RIX': ['LV', '拉脱维亚·Riga'],
    'RUH': ['SA', '沙特阿拉伯·利雅得'],
    'RUN': ['RE', '留尼汪·St Denis'],
    'SAN': ['US', '美国·圣迭戈'],
    'SAP': ['HN', '洪都拉斯·La Mesa'],
    'SAT': ['US', '美国·圣安东尼奥'],
    'SCL': ['CL', '智利·圣地亚哥'],
    'SDQ': ['DO', '多米尼加·Santo Domingo'],
    'SEA': ['US', '美国·西雅图'],
    'SFO': ['US', '美国·旧金山'],
    'SGN': ['VN', '越南·Ho Chi Minh City'],
    'SHA': ['CN', '中国·上海'],
    'SIN': ['SG', '新加坡'],
    'SJC': ['US', '美国·圣何塞'],
    'SJK': ['BR', '巴西·Sao Jose Dos Campos'],
    'SJO': ['CR', '哥斯达黎加·圣何塞'],
    'SJP': ['BR', '巴西·Sao Jose Do Rio Preto'],
    'SJU': ['PR', '波多黎各·圣胡安'],
    'SJW': ['CN', '中国·Hengshui'],
    'SKG': ['GR', '希腊·塞萨洛尼基'],
    'SKP': ['MK', '北马其顿·Skopje'],
    'SLC': ['US', '美国·盐湖城'],
    'SMF': ['US', '美国·Sacramento'],
    'SOD': ['BR', '巴西·Sorocaba'],
    'SOF': ['BG', '保加利亚·Sofia'],
    'SSA': ['BR', '巴西·Salvador'],
    'STI': ['DO', '多米尼加·圣地亚哥'],
    'STL': ['US', '美国·St Louis'],
    'STR': ['DE', '德国·Stuttgart'],
    'SUV': ['FJ', '斐济·Nausori'],
    'SYD': ['AU', '澳大利亚·悉尼'],
    'SZX': ['CN', '中国·深圳'],
    'TAO': ['CN', '中国·Qingdao'],
    'TBS': ['GE', '格鲁吉亚·第比利斯'],
    'TEN': ['CN', '中国·Tongren'],
    'TGU': ['HN', '洪都拉斯·特古西加尔巴'],
    'TIA': ['AL', '阿尔巴尼亚·Tirana'],
    'TLH': ['US', '美国·Tallahassee'],
    'TLL': ['EE', '爱沙尼亚·Tallinn'],
    'TLV': ['IL', '以色列·特拉维夫'],
    'TNA': ['CN', '中国·济南'],
    'TNR': ['MG', '马达加斯加·Antananarivo'],
    'TPA': ['US', '美国·坦帕'],
    'TPE': ['TW', '中国台湾·台北'],
    'TUN': ['TN', '突尼斯'],
    'TXL': ['DE', '德国·柏林'],
    'TYN': ['CN', '中国·Yangquan'],
    'UDI': ['BR', '巴西·Uberlandia'],
    'UDR': ['IN', '印度·Udaipur'],
    'UIO': ['EC', '厄瓜多尔·基多'],
    'ULN': ['MN', '蒙古·Ulan Bator'],
    'URT': ['TH', '泰国·Surat Thani'],
    'VCP': ['BR', '巴西·Campinas'],
    'VIE': ['AT', '奥地利·维也纳'],
    'VIX': ['BR', '巴西·Vitoria'],
    'VNO': ['LT', '立陶宛·Vilnius'],
    'VTE': ['LA', '老挝·万象'],
    'WAW': ['PL', '波兰·华沙'],
    'WDH': ['NA', '纳米比亚·Windhoek'],
    'WLG': ['NZ', '新西兰·惠灵顿'],
    'WRO': ['PL', '波兰·Wroclaw'],
    'XAP': ['BR', '巴西·Chapeco'],
    'XFN': ['CN', '中国·Xiangyang'],
    'XIY': ['CN', '中国·Baoji'],
    'XNH': ['IQ', '伊拉克·Nasiriyah'],
    'YHZ': ['CA', '加拿大·哈利法克斯'],
    'YUL': ['CA', '加拿大·蒙特利尔'],
    'YVR': ['CA', '加拿大·温哥华'],
    'YWG': ['CA', '加拿大·温尼伯'],
    'YXE': ['CA', '加拿大·Saskatoon'],
    'YYC': ['CA', '加拿大·卡尔加里'],
    'YYZ': ['CA', '加拿大·多伦多'],
    'ZAG': ['HR', '克罗地亚·Zagreb'],
    'ZDM': ['PS', '巴勒斯坦·Ramallah'],
    'ZRH': ['CH', '瑞士·苏黎世'],
}
